import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="h-full bg-gray-100">
            <body className="h-full">
                <header>
                    <nav className="bg-gray-800 p-4">
                        <div className="container mx-auto flex justify-between items-center">
                            <div className="text-white text-lg font-bold">
                                Next JS
                            </div>
                            <div className="space-x-4">
                                <Link
                                    href="/"
                                    className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                                >
                                    Home
                                </Link>
                                <Link
                                    href="/about"
                                    className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                                >
                                    About
                                </Link>
                                <Link
                                    href="/contact"
                                    className="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                                >
                                    Contact
                                </Link>
                            </div>
                        </div>
                    </nav>
                </header>
                <main>
                    <div className="container mx-auto">{children}</div>
                </main>
                <footer></footer>
            </body>
        </html>
    );
}
